os: osx
before_install:
  - brew upgrade python
  - brew install neovim
install:
  - pip3 install -r requirements.txt
  - pip3 install --pre kallikrein
script:
  - klk unit
  - klk integration
env:
  - AMINO_LOG_DIR=/tmp/amino
after_failure:
  - cat /tmp/amino/*
